service: python-ab-test

provider:
  name: aws

  region: ${env:REGION, 'sa-east-1'}
  architecture: ${env:ARCHITECTURE, 'arm64'}
  runtime: python${env:PYTHON_VERSION, 3.12}

  environment:
    DD_COLD_START_TRACE_SKIP_LIB: none
    DD_MIN_COLD_START_DURATION: 0
    PYAB_INIT_API: false

package:
  patterns:
    - '!**'
    - 'handler.py'

plugins:
  - serverless-plugin-datadog

custom:
  datadog:
    apiKey: ${env:DD_API_KEY}
    addLayers: false

functions:
  before:
    handler: handler.handler
    url: true
    layers:
      # Change this to the before layer version you wish to compare
      - arn:aws:lambda:sa-east-1:425362996713:layer:Python312-REY:46

  after:
    handler: handler.handler
    url: true
    layers:
      # Change this to the after layer version you wish to compare
      - arn:aws:lambda:sa-east-1:425362996713:layer:Python312-REY:47
